### ISSUE TITLE
Please update the npm command

### ISSUE THREAD

**Issue by notacouch** [Denperidge/eleventy-auto-cache-buster#2]
Currently the instructions say to run:
`npm --save-dev eleventy-auto-cache-buster`

It's late, and I couldn't tell for the life of me why it wasn't working despite the error 'Unknown command: "eleventy-auto-cache-buster"'. Long story short... it's missing `install`.

so

`npm install --save-dev eleventy-auto-cache-buster`

Works great so far! Thank you!

For anyone else reading, for ESM support, instead of CJS `require` syntax you can just do:
`import eleventyAutoCacheBuster from "eleventy-auto-cache-buster";`

**Comment by Denperidge** [comment]
Hi! Super late reply, but updated the README (506fb48eb712a8c951f96383ccad4a5573dc2e74). Glad to hear it's working well, thanks for the Issue report!
