### ISSUE TITLE
Enhancement: add option for partial hashes

### ISSUE THREAD

**Issue by BenjaminEHowe** [Denperidge/eleventy-auto-cache-buster#3]
We probably don't need to include the full hash to meet our cache busting goal. Please could you add an option to only include (e.g.) the first 8 characters of the hash?

The number of characters should probably be configurable in case others disagree with me on how many characters to use ;-)

**Comment by Denperidge** [comment]
That’s a good idea! I’ll try to get on that in a couple of days, or if anyone has a PR feel free to submit.

**Comment by Denperidge** [comment]
Update: gave it a spin, should be available from 0.4.0/92b719449f693d69ed00c5a368c0e84349a7acf3 ! Let me know if it works @BenjaminEHowe

**Comment by BenjaminEHowe** [comment]
Gold star for you! Will have a tinker later today and let you know.

**Comment by BenjaminEHowe** [comment]
LGTM! See https://github.com/BenjaminEHowe/11ty-links/commit/7239eaf670d9ac4ab6c20d6abc129f99a6df309b and the source code of https://8c93565f.11ty-links.pages.dev. Thank you :-)
